---
title: "final"
format: html
---

https://github.com/misssammwoods04/ENVS-193DS_spring-2025_final

```{r}
library(tidyverse)
library(janitor)
library(ggplot2)
library(here)
library(DHARMa)
library(ggeffects)
```


# Problem 1

## a.

In part one, one co-worker used a linear regression test. In part two, they used and analysis of variance test (ANOVA). 

## b. 

The F distribution should be included to provide more context because it would help us determine significance, which helps us assess whether the observed differences are likely due to an actual relationship or random variation. since ANOVA only tells us that at least one group differs from the others, it would be important to conduct a post-hoc test (such as Tukey’s HSD) to identify which specific groups differ significantly from each other.

## c.

We found a strong correlation between annual total nitrogen laod nitrogen load (kg/year) and distance from the headwater (km) (Linear regression, r value, F distribution, p = 0.03, $\alpha$ = significance level)

Average nitrogen load (kg year⁻¹) differed significantly among nitrogen sources. Post-hoc testing confirmed significant differences between certain categories (One-way ANOVA, F distribution, Tukey HSD post-hoc test, p = 0.02, $\alpha$ = significance level)



# Problem 4

## a. 


My homework 3 visualization is a lot more detailed and creative and includes all my predictor variables while my initial visualization shows only one predictor variable. Also, my initial visualization is more straightforward because it is a simple graph while my final visualization is more complex. 
